// Elm application entry point with Phoenix socket integration
// @ts-ignore - Elm types will be generated by esbuild-plugin-elm
import { Elm } from "../src/Main.elm";
import { connectSocket } from "./socket";

interface ElmApp {
  ports: {
    joinGame: { subscribe: (callback: (data: unknown) => void) => void };
    leaveGame: { subscribe: (callback: () => void) => void };
    sendDirection: { subscribe: (callback: (data: unknown) => void) => void };
    receiveGameState: { send: (data: unknown) => void };
    receiveError: { send: (message: string) => void };
    playerJoined: { send: (data: unknown) => void };
    playerLeft: { send: (data: unknown) => void };
    receiveTick: { send: (data: unknown) => void };
  };
}

// Wait for DOM to be ready
document.addEventListener("DOMContentLoaded", () => {
  const elmNode = document.getElementById("elm-app");

  if (!elmNode) {
    console.error("Could not find #elm-app element");
    return;
  }

  // Initialize Elm application
  const app: ElmApp = Elm.Main.init({
    node: elmNode,
  });

  console.log("Elm app initialized");

  // Connect Phoenix socket and wire to Elm ports
  connectSocket(app);
});
