// Elm application entry point with Phoenix socket and PeerJS integration
// @ts-ignore - Elm types will be generated by esbuild-plugin-elm
import { Elm } from "../src/Main.elm";
import { connectSocket } from "./socket";
import { setupPeerPorts } from "./peerjs-ports";
import { setupQRPorts } from "./qr-generator";

interface ElmApp {
  ports: {
    // Phoenix socket ports (online mode)
    joinGame: { subscribe: (callback: (data: unknown) => void) => void };
    leaveGame: { subscribe: (callback: () => void) => void };
    sendDirection: { subscribe: (callback: (data: unknown) => void) => void };
    receiveGameState: { send: (data: unknown) => void };
    receiveError: { send: (message: string) => void };
    playerJoined: { send: (data: unknown) => void };
    playerLeft: { send: (data: unknown) => void };
    receiveTick: { send: (data: unknown) => void };
    // P2P ports (PeerJS)
    createRoom: { subscribe: (callback: (data: null) => void) => void };
    joinRoom: { subscribe: (callback: (roomCode: string) => void) => void };
    leaveRoom: { subscribe: (callback: () => void) => void };
    copyToClipboard: { subscribe: (callback: (text: string) => void) => void };
    broadcastGameState: { subscribe: (callback: (data: string) => void) => void };
    sendInputP2P: { subscribe: (callback: (data: string) => void) => void };
    roomCreated: { send: (roomCode: string) => void };
    peerConnected: {
      send: (data: { role: string; peerId?: string; roomCode?: string; myPeerId?: string }) => void;
    };
    peerDisconnected: { send: (peerId: string) => void };
    connectionError: { send: (message: string) => void };
    clipboardCopySuccess: { send: (data: null) => void };
    receiveGameStateP2P: { send: (data: string) => void };
    receiveInputP2P: { send: (data: string) => void };
    // Mode persistence port
    saveMode: { subscribe: (callback: (mode: string) => void) => void };
    // QR code generation ports
    generateQRCode: { subscribe: (callback: (url: string) => void) => void };
    qrCodeGenerated: { send: (result: { success: boolean; dataUrl?: string; error?: string }) => void };
  };
}

// Wait for DOM to be ready
document.addEventListener("DOMContentLoaded", () => {
  const elmNode = document.getElementById("elm-app");

  if (!elmNode) {
    console.error("Could not find #elm-app element");
    return;
  }

  // Read saved mode from localStorage ('p2p' | 'phoenix' | null)
  const savedMode = localStorage.getItem("snaker-mode");

  // Initialize Elm application with flags
  const app: ElmApp = Elm.Main.init({
    node: elmNode,
    flags: { savedMode: savedMode },
  });

  console.log("Elm app initialized");

  // Prevent arrow keys from scrolling the page
  document.addEventListener("keydown", (e) => {
    if (["ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"].includes(e.key)) {
      e.preventDefault();
    }
  });

  // Connect Phoenix socket and wire to Elm ports
  connectSocket(app);

  // Setup PeerJS port handlers for P2P connections
  setupPeerPorts(app);

  // Setup QR code generation ports
  setupQRPorts(app as any);

  // Subscribe to mode persistence port
  app.ports.saveMode.subscribe((mode: string) => {
    localStorage.setItem("snaker-mode", mode);
  });
});
