// Elm application entry point
// @ts-ignore - Elm types will be generated by esbuild-plugin-elm
import { Elm } from "../src/Main.elm";

interface ElmApp {
  ports: {
    joinGame: { subscribe: (callback: (data: unknown) => void) => void };
    leaveGame: { subscribe: (callback: () => void) => void };
    sendDirection: { subscribe: (callback: (data: unknown) => void) => void };
    receiveGameState: { send: (data: unknown) => void };
    receiveError: { send: (message: string) => void };
    playerJoined: { send: (data: unknown) => void };
    playerLeft: { send: (data: unknown) => void };
    receiveTick: { send: (data: unknown) => void };
  };
}

// Initialize Elm application
const app: ElmApp = Elm.Main.init({
  node: document.getElementById("elm-app"),
});

// Temporary: log port activity for debugging
app.ports.joinGame.subscribe((data) => {
  console.log("Port: joinGame", data);
});

app.ports.sendDirection.subscribe((data) => {
  console.log("Port: sendDirection", data);
});

console.log("Elm app initialized with ports");
